// Turns a GeoJSON of the Brazilian states (properties.sigla = UF code) into charts/brazil-map.js:
// simplified SVG paths in a 1000-wide viewBox, plus a label point per state.
// Usage: node scripts/make-map.mjs <states.geojson>
// Source used: click_that_hood brazil-states.geojson (IBGE state borders).
import { readFile, writeFile } from "node:fs/promises";

const file = process.argv[2];
if (!file) { console.error("Usage: node scripts/make-map.mjs <states.geojson>"); process.exit(1); }
const geo = JSON.parse(await readFile(file, "utf8"));

const EPS = 0.04;        // simplification tolerance, in degrees (about 4 km)
const MIN_AREA = 0.03;   // drop islands smaller than this (square degrees), keeping each state's largest ring

function rdp(pts, eps) {
  if (pts.length < 3) return pts;
  const [ax, ay] = pts[0], [bx, by] = pts[pts.length - 1];
  const dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy) || 1e-12;
  let idx = 0, dmax = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / len;
    if (d > dmax) { dmax = d; idx = i; }
  }
  if (dmax <= eps) return [pts[0], pts[pts.length - 1]];
  return [...rdp(pts.slice(0, idx + 1), eps).slice(0, -1), ...rdp(pts.slice(idx), eps)];
}
// Rings are closed (first point = last point), so split at the point farthest from the start before simplifying.
function simplifyRing(r, eps) {
  let far = 1, dmax = 0;
  for (let i = 1; i < r.length - 1; i++) { const d = Math.hypot(r[i][0] - r[0][0], r[i][1] - r[0][1]); if (d > dmax) { dmax = d; far = i; } }
  return [...rdp(r.slice(0, far + 1), eps).slice(0, -1), ...rdp(r.slice(far), eps)];
}
const area = (r) => Math.abs(r.reduce((s, [x, y], i) => { const [x2, y2] = r[(i + 1) % r.length]; return s + (x * y2 - x2 * y); }, 0) / 2);

const states = {};
let lonMin = 180, lonMax = -180, latMin = 90, latMax = -90;
for (const f of geo.features) {
  const polys = f.geometry.type === "MultiPolygon" ? f.geometry.coordinates : [f.geometry.coordinates];
  const rings = polys.map((p) => p[0]); // outer rings only
  const biggest = Math.max(...rings.map(area));
  const kept = rings.filter((r) => area(r) >= MIN_AREA || area(r) === biggest).map((r) => simplifyRing(r, EPS)).filter((r) => r.length >= 4);
  states[f.properties.sigla] = kept;
  for (const r of kept) for (const [x, y] of r) { lonMin = Math.min(lonMin, x); lonMax = Math.max(lonMax, x); latMin = Math.min(latMin, y); latMax = Math.max(latMax, y); }
}

// Equirectangular projection with the longitude scaled by cos(mid latitude).
const k = Math.cos((((latMin + latMax) / 2) * Math.PI) / 180);
const scale = 1000 / ((lonMax - lonMin) * k);
const px = (lon) => (lon - lonMin) * k * scale, py = (lat) => (latMax - lat) * scale;
const r1 = (n) => Math.round(n * 10) / 10;

const out = {};
for (const [uf, rings] of Object.entries(states)) {
  const d = rings.map((r) => "M" + r.map(([x, y]) => `${r1(px(x))} ${r1(py(y))}`).join("L") + "Z").join("");
  // Label point: area-weighted centroid of the largest ring.
  const big = rings.reduce((a, b) => (area(a) >= area(b) ? a : b)).map(([x, y]) => [px(x), py(y)]);
  let a2 = 0, cx = 0, cy = 0;
  big.forEach(([x, y], i) => { const [x2, y2] = big[(i + 1) % big.length]; const c = x * y2 - x2 * y; a2 += c; cx += (x + x2) * c; cy += (y + y2) * c; });
  out[uf] = { cx: r1(cx / (3 * a2)), cy: r1(cy / (3 * a2)), d };
}
const height = Math.ceil((latMax - latMin) * scale);
const body = Object.keys(out).sort().map((uf) => `  ${uf}: ${JSON.stringify(out[uf])},`).join("\n");
await writeFile("charts/brazil-map.js",
  `// Generated by scripts/make-map.mjs from IBGE state borders (simplified). Do not edit by hand.\n` +
  `export const MAP = { width: 1000, height: ${height}, states: {\n${body}\n} };\n`);
console.log("states", Object.keys(out).length, "height", height, "bytes", (await readFile("charts/brazil-map.js")).length);
